# MODEL PATH
BASE_MODEL_PATH = "models"

#CONFIG PATH
DEFAULT_CONFIG_PATH= "config/config.ini"

#OPCO
NIGERIA_OPCO="NIGERIA"

#OPCO TYPE SECTION
OPCO_TYPE_SECTION="OPCO"
OPCO_NAME_KEY="NAME"

#FILENAME_KEYS
ID_IMG_KEY="ID_IMG"
SUB_IMAGE_KEY="SUB_IMAGE"
ID_IMG_ENHANCED_KEY="ID_IMG_ENHANCED"
ID_IMG_DENOISED_KEY="ID_IMG_DENOISED"
ID_IMG_FACE_KEY="ID_IMG_FACE"
SUB_IMG_FACE_KEY="SUB_IMG_FACE"
SUB_IMG_KEY="SUB_IMG"
FACE_VERIFICATION_IMG_INP_ID_KEY="FACE_VERIFICATION_IMG_INP_ID"
THRESHOLD_KEY="THRESHOLD"